Video 6759 results mobile styling
twilio/twilio-video-diagnostics-react-app pull request #37
Opened 2022-03-08 00:04 UTC by olipyskoty

**Contributing to Twilio**

> All third party contributors acknowledge that any contributions they provide will be made under the same open source license that the open source project is provided under.

- [x] I acknowledge that all my contributions will be made under the project's license.

## Pull Request Details

### JIRA link(s):

- [VIDEO-6759](https://issues.corp.twilio.com/browse/VIDEO-6759)

### Description

This PR adds mobile designs for the Results page. Instead of making the pane scrollable, I made some of the padding and margins smaller, though I am open to other suggestions.

**iPad Air Screenshots**:
![IMG_0017](https://user-images.githubusercontent.com/77076398/157138836-1d52241d-dc8a-4920-b79a-3f75fafec27c.PNG)

![IMG_0018](https://user-images.githubusercontent.com/77076398/157138875-98103da9-1419-4e78-916d-2c7fd94086d9.PNG)

## Burndown

### Before review
* [ ] Updated CHANGELOG.md if necessary
* [x] Added unit tests if necessary
* [ ] Updated affected documentation
* [x] Verified locally with `npm test`
* [x] Manually sanity tested running locally
* [x] Included screenshot as PR comment (if needed)
* [x] Ready for review

### Before merge
* [ ] Got one or more +1s
* [ ] Re-tested if necessary

2022-03-09 04:55 UTC, timmydoza requested changes
Looks great! Nice implementation!

Just wanted to also mention the potential bug we talked about, where the user should not be able to proceed past this screen when there is an error:
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/12685223/157374930-54f3bf47-29c3-44ed-ba50-c2fed4265c27.png">

Not sure why this is happening. Does it correctly stop the user when there is a real error? In my case, my token server has expired, so if this works right for real errors then maybe this issue can be solved when we add an error for an expired server. 

Also, I was poking around, and I think we also need to apply mobile styles to the Snackbar as well:
![image](https://user-images.githubusercontent.com/12685223/157375523-cbaf7dd0-008e-4482-a52e-8df35b8ec33d.png)

2022-03-09 04:55 UTC, timmydoza commented on src/components/panes/Results/Results.tsx
> +      },
Here I wonder if some `padding-bottom` would help to give a bit more room between the buttons and the results. It's subtle.

```
      [theme.breakpoints.down('md')]: {
        float: 'initial',
        paddingBottom: '1em'
      },
``` 

Before:
<img width="280" alt="image" src="https://user-images.githubusercontent.com/12685223/157374660-596c2965-bebc-4709-a872-44db9a0f77b3.png">

After:
<img width="282" alt="image" src="https://user-images.githubusercontent.com/12685223/157374682-8550f1aa-f1fb-4892-8627-6c28255cbfa7.png">

2022-03-11 22:28 UTC, olipyskoty commented
> Looks great! Nice implementation!
> 
> Just wanted to also mention the potential bug we talked about, where the user should not be able to proceed past this screen when there is an error: 
> 
> Not sure why this is happening. Does it correctly stop the user when there is a real error? In my case, my token server has expired, so if this works right for real errors then maybe this issue can be solved when we add an error for an expired server.
> 
> Also, I was poking around, and I think we also need to apply mobile styles to the Snackbar as well:

Looks like we were correctly disabling the down arrow button when the preflight test failed, but we weren't hiding the following pane. We were not accounting for the `preflight-token-failed` at all however. So I added this to the logic for disabling the down button, and hiding the following pane. I think it will be good to include this behavior even though the user may not even be able to make it past the "Get Started" pane once we implement the expired server error handling.

2022-03-14 22:03 UTC, timmydoza approved these changes
Looks great - nice work! 

I think the Snackbar component could use an error that explains when it is shown to the user, but other than that I think this is good to go!

2022-03-14 22:40 UTC, merged